# Generated by Django 5.2.17 on 2026-09-08 15:16

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexiblePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 7), ('rich_text', 9), ('image', 12), ('feature_grid', 22), ('cta_band', 25), ('faq', 29), ('stats', 34), ('testimonials', 38)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional background image', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 40}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Internal route, e.g. /umrah', 'max_length': 200}), 6: ('wagtail.blocks.StructBlock', [[('label', 4), ('href', 5)]], {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('subheading', 2), ('image', 3), ('cta', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote']}), 9: ('wagtail.blocks.StructBlock', [[('text', 8)]], {}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('image', 10), ('caption', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Phosphor icon name used by the frontend, e.g. IdentificationCard', 'max_length': 60, 'required': False}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 17: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'Internal route, e.g. /umrah', 'max_length': 200, 'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': "Button/link text, e.g. 'Open chat'", 'max_length': 60, 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('icon_name', 14), ('image', 15), ('label', 16), ('body', 17), ('href', 18), ('action_label', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.StructBlock', [[('heading', 13), ('items', 21)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('label', 4), ('href', 5)]], {}), 25: ('wagtail.blocks.StructBlock', [[('heading', 1), ('body', 23), ('cta', 24)]], {}), 26: ('wagtail.blocks.TextBlock', (), {}), 27: ('wagtail.blocks.StructBlock', [[('question', 17), ('answer', 26)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {}), 29: ('wagtail.blocks.StructBlock', [[('heading', 13), ('items', 28)]], {}), 30: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 31: ('wagtail.blocks.CharBlock', (), {'max_length': 20}), 32: ('wagtail.blocks.StructBlock', [[('label', 30), ('figure', 31)]], {}), 33: ('wagtail.blocks.ListBlock', (32,), {}), 34: ('wagtail.blocks.StructBlock', [[('heading', 13), ('items', 33)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'max_length': 140}), 36: ('wagtail.blocks.StructBlock', [[('quote', 26), ('name', 16), ('detail', 35)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {}), 38: ('wagtail.blocks.StructBlock', [[('heading', 13), ('items', 37)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
