# Generated by Django 5.2.17 on 2026-09-23 14:18

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


def seed_landing_content(apps, schema_editor):
    Landing = apps.get_model("flexpages", "CatalogueLandingContent")
    records = {
        "umrah": {
            "hero_eyebrow": "Umrah",
            "hero_heading": "Find your Umrah package",
            "hero_subheading": "Filter by duration, category, hotel and price to browse ready-made packages, or build your own from scratch. Prices are estimates until confirmed by our team.",
            "copies": [
                ("builder_intro", "Build your package", "Build around the details that matter to you", "The total updates as you choose a category, dates, hotels, room sharing and transport. Start from a listed package or configure each part yourself."),
                ("process_intro", "How it works", "From package choice to a clear quote", "The builder keeps your choices together and shows the estimate as you go."),
            ],
            "faq_heading": "Umrah package questions",
            "faqs": [
                ("How is the estimate calculated?", "It updates with your selected category, duration, hotels, room sharing, transport and any additional services. The review step shows the itemised estimate before you submit."),
                ("Can I change a ready-made package?", "Yes. Selecting a package fills in its defaults, and you can continue through the builder to review or change the available choices."),
                ("Can I choose my own hotels?", "Yes. The hotel step lists the available Makkah and Madinah options with their star rating and distance."),
                ("Does this builder book flights?", "No. This builder estimates the Umrah ground-service package: hotels, visa processing, transport and optional services."),
            ],
        },
        "hajj": {
            "hero_eyebrow": "Hajj", "hero_heading": "A place for the season",
            "hero_subheading": "Hajj allocation is genuinely limited, so it isn't a filter: it's a short list of fixed packages grouped by type, each with its own quota and application deadline. Open one to see what's included and request a place.",
            "copies": [
                ("rites_intro", "The rites", "A clear outline of the Hajj journey", "The order below follows the itinerary published with the packages. Your selected package page has its full plan and accommodation details."),
                ("comparison_intro", "Compare the options", "Hajj package details", "Quotas, deadlines, duration and prices come from each package listing."),
            ],
            "faq_heading": "Hajj, at a glance",
            "faqs": [
                ("How much do Hajj packages cost?", "Each package listing shows its current price, duration, quota and application deadline."),
                ("How do the package types differ?", "Compare the accommodation, transport, meals and guide details on each package page, alongside the quota and deadline in the table above."),
                ("When should I apply?", "Each package has its own application deadline and quota. Check both on the package you are considering and apply before its deadline."),
                ("What is included?", "Inclusions vary by package. Open a package to review its accommodation, transport, meals, guide and itinerary before enquiring."),
            ],
        },
        "tours": {
            "hero_eyebrow": "Tours", "hero_heading": "International Tour Packages",
            "hero_subheading": "Guided tours across Turkey, Thailand, Dubai, Malaysia, Europe and more. Filter by country, duration, price, group type or season, then open a package for the full itinerary.",
            "copies": [
                ("season_intro", "Plan by season", "Find a trip for the time you have", "Every package is tagged with a season. Compare the available itineraries below, then use the filters above to narrow by country, duration, group type or price."),
                ("travel_style_intro", "Travel style", "Who is each itinerary for?", "These groups reflect the travel-style tags attached to the current package listings."),
            ],
            "faq_heading": "International tours, at a glance",
            "faqs": [
                ("Which countries are available?", "Use the country filter to see the available packages for each destination."),
                ("How do I compare itineraries?", "Each package page lists its duration, season, itinerary, inclusions, exclusions and accommodation details."),
                ("Can I find a package for a particular travel style?", "The package cards are tagged by group type. Use the group-type filter or the list above to see matching itineraries."),
                ("How much do the tours cost?", "Prices vary by destination, duration and season. Each package card shows its current from-price, and the detail page explains what is included."),
            ],
        },
        "pakistan-tours": {
            "hero_eyebrow": "Tours", "hero_heading": "Pakistan Tour Packages",
            "hero_subheading": "From Hunza's glacial lakes to a family weekend in Murree. Filter by region, duration, price, group type or season, then open a package for the full itinerary.",
            "copies": [
                ("region_intro", "Explore the regions", "Choose where to go", "Browse the destinations represented in the current catalogue. Each route page has its own itinerary, duration, accommodation and inclusions."),
                ("season_intro", "Timing", "Packages by season", "Season labels follow the availability recorded for each package."),
            ],
            "faq_heading": "Pakistan tours, at a glance",
            "faqs": [
                ("Which regions are represented?", "Browse the index above or use the region filter to find a route."),
                ("When should I travel?", "Each package is tagged with a season. Open a package for its itinerary and accommodation details before choosing dates."),
                ("How long are the trips?", "Durations vary by route. The package cards show the number of days, and each detail page has the full itinerary."),
                ("What is included in the price?", "Inclusions are listed on each package detail page, along with the stays and day-by-day itinerary."),
            ],
        },
    }
    for key, record in records.items():
        sections = [
            {"type": "copy", "value": {"slot": slot, "eyebrow": eyebrow, "heading": heading, "body": body}}
            for slot, eyebrow, heading, body in record["copies"]
        ]
        sections.append({"type": "faq", "value": {
            "heading": record["faq_heading"],
            "items": [{"question": q, "answer": a} for q, a in record["faqs"]],
        }})
        Landing.objects.get_or_create(
            page_key=key,
            defaults={
                "hero_eyebrow": record["hero_eyebrow"],
                "hero_heading": record["hero_heading"],
                "hero_subheading": record["hero_subheading"],
                "sections": sections,
            },
        )


def unseed_landing_content(apps, schema_editor):
    apps.get_model("flexpages", "CatalogueLandingContent").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('flexpages', '0009_alter_flexiblepage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueLandingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('umrah', 'Umrah'), ('hajj', 'Hajj'), ('tours', 'International Tours'), ('pakistan-tours', 'Pakistan Tours')], max_length=32, unique=True)),
                ('hero_eyebrow', models.CharField(blank=True, max_length=80)),
                ('hero_heading', models.CharField(blank=True, max_length=160)),
                ('hero_subheading', models.TextField(blank=True)),
                ('hero_image_alt', models.CharField(blank=True, max_length=160)),
                ('sections', wagtail.fields.StreamField([('copy', 4), ('faq', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Stable section key used by the frontend, e.g. season_intro', 'max_length': 60}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('slot', 0), ('eyebrow', 1), ('heading', 2), ('body', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Common questions', 'max_length': 120, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('question', 6), ('answer', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'default': [{'answer': 'For Ramadan, three to four months. Off-peak, six weeks is usually enough.', 'question': 'How far in advance should I book?'}, {'answer': 'Yes, the visa is included and handled for you on every package.', 'question': 'Do you arrange the visa?'}]}), 10: ('wagtail.blocks.StructBlock', [[('heading', 5), ('items', 9)]], {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'catalogue landing content',
                'verbose_name_plural': 'catalogue landing content',
                'ordering': ['page_key'],
            },
        ),
        migrations.RunPython(seed_landing_content, unseed_landing_content),
    ]
