# Generated by Django 5.2.17 on 2026-09-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
    ]
