# Generated by Django 5.2.17 on 2026-09-15 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HajjPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('package_type', models.CharField(choices=[('Government Scheme', 'Government Scheme'), ('Private Economy', 'Private Economy'), ('Private Premium', 'Private Premium')], max_length=20)),
                ('strap', models.CharField(max_length=160)),
                ('blurb', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('nights', models.PositiveSmallIntegerField()),
                ('from_price_gbp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quota_text', models.CharField(max_length=80)),
                ('application_deadline', models.CharField(max_length=80)),
                ('transport_text', models.CharField(max_length=200)),
                ('meals_text', models.CharField(max_length=200)),
                ('guide_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PakistanRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='TourCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Tour countries',
            },
        ),
        migrations.CreateModel(
            name='UmrahAddOnService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('note', models.CharField(max_length=200)),
                ('price_gbp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pricing_unit', models.CharField(choices=[('person', 'Per person'), ('booking', 'Per booking'), ('day', 'Per day')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UmrahCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('strap', models.CharField(max_length=160)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Umrah categories',
            },
        ),
        migrations.CreateModel(
            name='UmrahPricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_price_gbp', models.DecimalField(decimal_places=2, default=180, max_digits=8)),
                ('airport_transfer_price_gbp', models.DecimalField(decimal_places=2, default=25, max_digits=8)),
                ('ziyarat_price_gbp', models.DecimalField(decimal_places=2, default=45, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'Umrah pricing settings',
            },
        ),
        migrations.CreateModel(
            name='UmrahRoomSharingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=80)),
                ('note', models.CharField(max_length=160)),
                ('divisor', models.PositiveSmallIntegerField(help_text='How many travellers split one room-night.')),
            ],
        ),
        migrations.CreateModel(
            name='UmrahTransportTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=80)),
                ('note', models.CharField(max_length=160)),
                ('price_gbp', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='HajjItineraryStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('day_label', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='packages.hajjpackage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HajjGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(max_length=500)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='packages.hajjpackage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HajjAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(choices=[('Makkah', 'Makkah'), ('Madinah', 'Madinah'), ('Mina', 'Mina'), ('Arafat', 'Arafat')], max_length=10)),
                ('detail', models.CharField(max_length=300)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation', to='packages.hajjpackage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PakistanTourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('strap', models.CharField(max_length=160)),
                ('blurb', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('from_price_gbp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('season', models.CharField(choices=[('Ramadan', 'Ramadan'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Year-round', 'Year-round')], max_length=12)),
                ('featured', models.BooleanField(default=False)),
                ('card_tag', models.CharField(blank=True, choices=[('Family', 'Family'), ('Honeymoon', 'Honeymoon'), ('Group', 'Group')], max_length=10)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='packages.pakistanregion')),
            ],
        ),
        migrations.CreateModel(
            name='PakistanTourItineraryStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('day_label', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='packages.pakistantourpackage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PakistanTourInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=300)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='packages.pakistantourpackage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PakistanTourGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(max_length=500)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='packages.pakistantourpackage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PakistanTourStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=120)),
                ('stay_type', models.CharField(choices=[('Hotel', 'Hotel'), ('Resort', 'Resort'), ('Guesthouse', 'Guesthouse'), ('Camping', 'Camping')], max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('detail', models.CharField(max_length=300)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='packages.pakistantourpackage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('strap', models.CharField(max_length=160)),
                ('blurb', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('from_price_gbp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('season', models.CharField(choices=[('Ramadan', 'Ramadan'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Year-round', 'Year-round')], max_length=12)),
                ('featured', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='packages.tourcountry')),
            ],
        ),
        migrations.CreateModel(
            name='TourItineraryStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('day_label', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='packages.tourpackage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TourInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=300)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='packages.tourpackage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TourHotelStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(max_length=80)),
                ('hotel_name', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField()),
                ('detail', models.CharField(max_length=300)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='packages.tourpackage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TourGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(max_length=500)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='packages.tourpackage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TourExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=300)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='packages.tourpackage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UmrahHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(choices=[('Makkah', 'Makkah'), ('Madinah', 'Madinah')], max_length=10)),
                ('distance_label', models.CharField(max_length=80)),
                ('distance_meters', models.PositiveIntegerField()),
                ('star_rating', models.PositiveSmallIntegerField()),
                ('price_per_night_gbp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image_url', models.URLField(max_length=500)),
                ('categories', models.ManyToManyField(related_name='hotels', to='packages.umrahcategory')),
            ],
        ),
        migrations.CreateModel(
            name='UmrahPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('strap', models.CharField(max_length=160)),
                ('blurb', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('season', models.CharField(choices=[('Ramadan', 'Ramadan'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Year-round', 'Year-round')], max_length=12)),
                ('from_price_gbp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('popular', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='packages.umrahcategory')),
                ('madinah_hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='packages.umrahhotel')),
                ('makkah_hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='packages.umrahhotel')),
                ('room_sharing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='packages.umrahroomsharingoption')),
                ('transport_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='packages.umrahtransporttier')),
            ],
        ),
        migrations.CreateModel(
            name='UmrahPackageInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=300)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='packages.umrahpackage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PakistanTourPackageGroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('Individual', 'Individual'), ('Family', 'Family'), ('Couple', 'Couple'), ('Group', 'Group')], max_length=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_types', to='packages.pakistantourpackage')),
            ],
            options={
                'unique_together': {('package', 'group_type')},
            },
        ),
        migrations.CreateModel(
            name='TourPackageGroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('Individual', 'Individual'), ('Family', 'Family'), ('Couple', 'Couple'), ('Group', 'Group')], max_length=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_types', to='packages.tourpackage')),
            ],
            options={
                'unique_together': {('package', 'group_type')},
            },
        ),
        migrations.CreateModel(
            name='UmrahPackageAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='packages.umrahaddonservice')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_addons', to='packages.umrahpackage')),
            ],
            options={
                'unique_together': {('package', 'addon_service')},
            },
        ),
    ]
