# Generated by Django 5.2.17 on 2026-09-17 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archetype', models.CharField(choices=[('hajj', 'Hajj'), ('umrah', 'Umrah'), ('tours', 'International Tours'), ('pakistan-tours', 'Pakistan Tours')], max_length=20)),
                ('csv_file', models.FileField(upload_to='package_imports/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('committed', 'Committed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('result_summary', models.JSONField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Package import batches',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
