# Generated by Django 5.2.17 on 2026-09-08 10:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='sections',
            field=wagtail.fields.StreamField([('checklist', 3), ('steps', 7), ('tile_grid', 16), ('paragraph', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 300}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('items', 2)]], {}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('steps', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Phosphor icon name used by the frontend, e.g. IdentificationCard', 'max_length': 60, 'required': False}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Internal route, e.g. /umrah', 'max_length': 200, 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': "Button/link text, e.g. 'Open chat'", 'max_length': 60, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('icon_name', 8), ('image', 9), ('label', 10), ('body', 11), ('href', 12), ('action_label', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('title', 0), ('tiles', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 18: ('wagtail.blocks.RichTextBlock', (), {}), 19: ('wagtail.blocks.StructBlock', [[('title', 17), ('text', 18)]], {'icon': 'pilcrow'})}),
        ),
    ]
