# Generated by Django 5.2.17 on 2026-09-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicepage_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='eyebrow',
            field=models.CharField(blank=True, help_text='Small kicker label above the title. Leave blank to use "<site title> services".', max_length=80),
        ),
    ]
