# Generated by Django 5.2.17 on 2026-09-08 10:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('category_cards', 7), ('highlights', 8), ('testimonials', 12), ('faqs', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Phosphor icon name used by the frontend, e.g. IdentificationCard', 'max_length': 60, 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Internal route, e.g. /umrah', 'max_length': 200, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Button/link text, e.g. 'Open chat'", 'max_length': 60, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('icon_name', 0), ('image', 1), ('label', 2), ('body', 3), ('href', 4), ('action_label', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Category cards'}), 8: ('wagtail.blocks.ListBlock', (6,), {'label': 'Highlights'}), 9: ('wagtail.blocks.TextBlock', (), {}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 140}), 11: ('wagtail.blocks.StructBlock', [[('quote', 9), ('name', 2), ('detail', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Testimonials'}), 13: ('wagtail.blocks.StructBlock', [[('question', 3), ('answer', 9)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'label': 'FAQ'})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='Halcyon', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subheading',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField(blank=True, help_text="Short description under the logo, e.g. 'An independent long-haul airline...'")),
                ('legal_line', models.CharField(blank=True, help_text="e.g. 'Halcyon Airways Ltd. This is a design prototype, not a real airline.'", max_length=200)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
