# Generated by Django 5.2.17 on 2026-09-08 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_homepage_hero_eyebrow_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Halcyon', help_text='Shown in the browser tab and the header/footer wordmark.', max_length=60)),
                ('theme', models.CharField(choices=[('rust', 'Rust (default)'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('midnight', 'Midnight')], default='rust', max_length=20)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
