# Generated by Django 5.2.17 on 2026-09-08 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sitesettings'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='color_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', "Follow the visitor's device setting")], default='light', help_text="Light or dark surfaces. 'Follow device' uses each visitor's OS light/dark setting.", max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Browser-tab icon. A square PNG works best.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Replaces the default mark in the header and footer. Leave empty to use the built-in wordmark.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('rust', 'Rust (default)'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('midnight', 'Midnight')], default='rust', help_text='The accent colour palette.', max_length=20),
        ),
    ]
