# Generated by Django 5.2.17 on 2026-09-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sitesettings_color_mode_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_eyebrow',
            field=models.CharField(blank=True, help_text='Small kicker above the hero heading. Leave blank to use the site title.', max_length=80),
        ),
    ]
