# Generated by Django 5.2.17 on 2026-09-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_hero_eyebrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='legal_line',
            field=models.CharField(blank=True, help_text='Legal-entity / copyright line. Leave blank to fall back to "<site title> is a design prototype, not a real airline."', max_length=200),
        ),
    ]
