# Generated by Django 5.2.17 on 2026-09-08 14:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('category_cards', 7), ('stats', 11), ('highlights', 12), ('testimonials', 16), ('faqs', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Phosphor icon name used by the frontend, e.g. IdentificationCard', 'max_length': 60, 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Internal route, e.g. /umrah', 'max_length': 200, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Button/link text, e.g. 'Open chat'", 'max_length': 60, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('icon_name', 0), ('image', 1), ('label', 2), ('body', 3), ('href', 4), ('action_label', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Category cards'}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 20}), 10: ('wagtail.blocks.StructBlock', [[('label', 8), ('figure', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Statistics (trust strip)'}), 12: ('wagtail.blocks.ListBlock', (6,), {'label': 'Highlights'}), 13: ('wagtail.blocks.TextBlock', (), {}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 140}), 15: ('wagtail.blocks.StructBlock', [[('quote', 13), ('name', 2), ('detail', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'label': 'Testimonials'}), 17: ('wagtail.blocks.StructBlock', [[('question', 3), ('answer', 13)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'label': 'FAQ'})}),
        ),
    ]
