# Generated by Django 5.2.17 on 2026-09-08 14:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='columns',
            field=wagtail.fields.StreamField([('column', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 40}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Internal route, e.g. /umrah', 'max_length': 200}), 3: ('wagtail.blocks.StructBlock', [[('label', 1), ('href', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 4)]], {})}, help_text="The footer's navigation columns. Leave empty to use the built-in Travel / Services / <site title> / Help columns."),
        ),
    ]
