# Generated by Django 5.2.17 on 2026-09-08 15:11

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_footersettings_columns'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_links', wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 40}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Internal route, e.g. /umrah, or a page you built (e.g. /pages/ramadan-offer)', 'max_length': 200}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('href', 1)]], {})}, help_text='Main navigation links. Leave empty for the built-in Umrah / Hajj / Tours / Manage trip / Help.')),
                ('cta_label', models.CharField(blank=True, help_text='Right-hand button label. Blank falls back to "Sign in".', max_length=40)),
                ('cta_href', models.CharField(blank=True, help_text='Where the button links. Blank falls back to /signin.', max_length=200)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
