# Generated by Django 5.2.17 on 2026-09-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_headersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number shown on the right of the utility strip. Blank falls back to +44 20 7946 0192.', max_length=40),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='tagline',
            field=models.CharField(blank=True, help_text='Small text on the left of the utility strip above the header. Blank falls back to "Flying from London Gatwick, Manchester and Edinburgh".', max_length=140),
        ),
    ]
