# Generated by Django 5.2.17 on 2026-09-08 10:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(blank=True, default='Help', max_length=80)),
                ('lede', models.TextField(blank=True)),
                ('body', wagtail.fields.StreamField([('channels', 7), ('faqs', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Phosphor icon name used by the frontend, e.g. IdentificationCard', 'max_length': 60, 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Internal route, e.g. /umrah', 'max_length': 200, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Button/link text, e.g. 'Open chat'", 'max_length': 60, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('icon_name', 0), ('image', 1), ('label', 2), ('body', 3), ('href', 4), ('action_label', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Contact channels'}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('question', 3), ('answer', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Common questions'})})),
                ('disruption_heading', models.CharField(blank=True, max_length=160)),
                ('disruption_steps', wagtail.fields.StreamField([('step', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 1)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
